import type { StoreTheme, StoreThemePreset } from "@/types";

export const storeThemePresets: Record<StoreThemePreset, StoreTheme> = {
  modern: {
    preset: "modern",
    accentColor: "#1769e0",
    backgroundColor: "#f5f8fc",
    surfaceColor: "#ffffff",
    textColor: "#101828",
    heroStyle: "cover",
    layout: "grid",
    font: "system",
    buttonStyle: "solid",
    cardRadius: 14,
    announcement: "",
  },
  boutique: {
    preset: "boutique",
    accentColor: "#8c5b3e",
    backgroundColor: "#fbf7f2",
    surfaceColor: "#fffdf9",
    textColor: "#2e2018",
    heroStyle: "split",
    layout: "editorial",
    font: "serif",
    buttonStyle: "pill",
    cardRadius: 22,
    announcement: "",
  },
  minimal: {
    preset: "minimal",
    accentColor: "#111827",
    backgroundColor: "#ffffff",
    surfaceColor: "#ffffff",
    textColor: "#111827",
    heroStyle: "minimal",
    layout: "grid",
    font: "system",
    buttonStyle: "outline",
    cardRadius: 4,
    announcement: "",
  },
  bold: {
    preset: "bold",
    accentColor: "#0d8b91",
    backgroundColor: "#07151a",
    surfaceColor: "#10242a",
    textColor: "#f5fbfc",
    heroStyle: "cover",
    layout: "editorial",
    font: "rounded",
    buttonStyle: "solid",
    cardRadius: 8,
    announcement: "",
  },
  luxury: {
    preset: "luxury",
    accentColor: "#c9a227",
    backgroundColor: "#0b0b0d",
    surfaceColor: "#161618",
    textColor: "#f2ede1",
    heroStyle: "cover",
    layout: "editorial",
    font: "serif",
    buttonStyle: "pill",
    cardRadius: 6,
    announcement: "",
  },
  pastel: {
    preset: "pastel",
    accentColor: "#d46a9a",
    backgroundColor: "#fdf2f8",
    surfaceColor: "#ffffff",
    textColor: "#3a2233",
    heroStyle: "minimal",
    layout: "grid",
    font: "rounded",
    buttonStyle: "pill",
    cardRadius: 22,
    announcement: "",
  },
  tech: {
    preset: "tech",
    accentColor: "#3b82f6",
    backgroundColor: "#0a0f1e",
    surfaceColor: "#111a30",
    textColor: "#eaf1ff",
    heroStyle: "split",
    layout: "grid",
    font: "system",
    buttonStyle: "outline",
    cardRadius: 10,
    announcement: "",
  },
  natural: {
    preset: "natural",
    accentColor: "#3f6b4a",
    backgroundColor: "#f6f1e7",
    surfaceColor: "#fffdf8",
    textColor: "#2b2a22",
    heroStyle: "split",
    layout: "editorial",
    font: "serif",
    buttonStyle: "solid",
    cardRadius: 16,
    announcement: "",
  },
  vibrant: {
    preset: "vibrant",
    accentColor: "#ff5b6e",
    backgroundColor: "#fffaf7",
    surfaceColor: "#ffffff",
    textColor: "#231317",
    heroStyle: "cover",
    layout: "grid",
    font: "rounded",
    buttonStyle: "pill",
    cardRadius: 18,
    announcement: "",
  },
  ocean: {
    preset: "ocean",
    accentColor: "#0891b2",
    backgroundColor: "#f0fbfc",
    surfaceColor: "#ffffff",
    textColor: "#0b2f38",
    heroStyle: "split",
    layout: "grid",
    font: "rounded",
    buttonStyle: "pill",
    cardRadius: 20,
    announcement: "",
  },
  sunset: {
    preset: "sunset",
    accentColor: "#ea580c",
    backgroundColor: "#fff7ed",
    surfaceColor: "#ffffff",
    textColor: "#431407",
    heroStyle: "cover",
    layout: "editorial",
    font: "serif",
    buttonStyle: "solid",
    cardRadius: 12,
    announcement: "",
  },
  monochrome: {
    preset: "monochrome",
    accentColor: "#e11d48",
    backgroundColor: "#ffffff",
    surfaceColor: "#fafafa",
    textColor: "#0a0a0a",
    heroStyle: "minimal",
    layout: "editorial",
    font: "system",
    buttonStyle: "outline",
    cardRadius: 0,
    announcement: "",
  },
  neon: {
    preset: "neon",
    accentColor: "#d946ef",
    backgroundColor: "#0a0118",
    surfaceColor: "#170a2e",
    textColor: "#f5e9ff",
    heroStyle: "cover",
    layout: "grid",
    font: "rounded",
    buttonStyle: "pill",
    cardRadius: 24,
    announcement: "",
  },
  royal: {
    preset: "royal",
    accentColor: "#065f46",
    backgroundColor: "#f2f7f4",
    surfaceColor: "#ffffff",
    textColor: "#0b2e22",
    heroStyle: "split",
    layout: "editorial",
    font: "serif",
    buttonStyle: "solid",
    cardRadius: 10,
    announcement: "",
  },
};

export function normalizeStoreTheme(theme?: Partial<StoreTheme>, fallbackAccent = "#1769e0"): StoreTheme {
  const preset = theme?.preset && storeThemePresets[theme.preset] ? theme.preset : "modern";
  const base = storeThemePresets[preset];
  return {
    ...base,
    ...theme,
    preset,
    accentColor: theme?.accentColor ?? fallbackAccent,
    cardRadius: Math.min(32, Math.max(0, Number(theme?.cardRadius ?? base.cardRadius))),
  };
}
