"use client";

import { FormEvent, useEffect, useState } from "react";
import { Bot, CheckCircle2, CircleOff, LoaderCircle, ShieldCheck, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { useApp } from "@/providers/app-provider";
import type { AIStatusResponse } from "@/types/ai";

export default function Page() {
  const { locale, platformSettings, updatePlatformSettings, resetDemo, productionMode } = useApp();
  const [settings, setSettings] = useState(platformSettings);
  const [status, setStatus] = useState<AIStatusResponse | null>(null);
  const [checking, setChecking] = useState(true);
  useEffect(() => {
    fetch("/api/ai/status", { cache: "no-store" })
      .then((response) => response.json())
      .then((data: AIStatusResponse) => setStatus(data))
      .finally(() => setChecking(false));
  }, []);
  async function submit(event: FormEvent) { event.preventDefault(); await updatePlatformSettings(settings); }

  return <>
    <PageHeader eyebrow="PLATFORM OPERATIONS" title={locale === "ar" ? "إعدادات المنصة" : "Platform settings"} text={locale === "ar" ? "تحكم مركزي في المراجعة والتسجيل والعمولة والرسائل وحدود الفيديو وتشغيل أدوات الذكاء الاصطناعي." : "Central control for moderation, registration, commission, messaging, video limits and AI tools."} />
    <form className="editor-form" onSubmit={submit}>
      <section className="editor-card"><div className="card-head"><div><span className="eyebrow">CORE SETTINGS</span><h3>{locale === "ar" ? "إعدادات التشغيل" : "Operational settings"}</h3></div></div><div className="form-grid two"><label className="field"><span>{locale === "ar" ? "اسم المنصة" : "Platform name"}</span><input value={settings.platformName} onChange={(event) => setSettings({ ...settings, platformName: event.target.value })} /></label><label className="field"><span>{locale === "ar" ? "بريد الدعم" : "Support email"}</span><input type="email" value={settings.supportEmail} onChange={(event) => setSettings({ ...settings, supportEmail: event.target.value })} /></label><label className="field"><span>{locale === "ar" ? "الحد الأقصى للريلز MB" : "Maximum reel size MB"}</span><input type="number" min={1} max={100} value={settings.maxReelSizeMB} onChange={(event) => setSettings({ ...settings, maxReelSizeMB: Number(event.target.value) })} /></label><label className="field"><span>{locale === "ar" ? "نسبة العمولة %" : "Commission %"}</span><input type="number" min={0} max={100} step="0.5" value={settings.commissionPercent} onChange={(event) => setSettings({ ...settings, commissionPercent: Number(event.target.value) })} /></label></div><div className="admin-toggle-list"><label><input type="checkbox" checked={settings.reelModerationRequired} onChange={(event) => setSettings({ ...settings, reelModerationRequired: event.target.checked })} /><div><strong>{locale === "ar" ? "إلزام مراجعة الريلز" : "Require reel moderation"}</strong><span>{locale === "ar" ? "لا يظهر أي ريلز للعامة قبل اعتماد الإدارة." : "No reel is public before admin approval."}</span></div></label><label><input type="checkbox" checked={settings.merchantRegistrationEnabled} onChange={(event) => setSettings({ ...settings, merchantRegistrationEnabled: event.target.checked })} /><div><strong>{locale === "ar" ? "السماح بتسجيل التجار" : "Allow merchant registration"}</strong><span>{locale === "ar" ? "إيقافه يمنع فتح حسابات تاجر جديدة." : "Disable to block new merchant accounts."}</span></div></label><label><input type="checkbox" checked={settings.messagingEnabled} onChange={(event) => setSettings({ ...settings, messagingEnabled: event.target.checked })} /><div><strong>{locale === "ar" ? "تشغيل الرسائل بين العملاء والمتاجر" : "Enable customer-store messaging"}</strong><span>{locale === "ar" ? "عند إيقافه تختفي أزرار المراسلة ويتوقف إرسال الردود." : "Disable to hide messaging actions and stop new replies."}</span></div></label><label><input type="checkbox" checked={settings.maintenanceMode} onChange={(event) => setSettings({ ...settings, maintenanceMode: event.target.checked })} /><div><strong>{locale === "ar" ? "وضع الصيانة" : "Maintenance mode"}</strong><span>{locale === "ar" ? "استخدمه عند تنفيذ تحديثات تشغيلية كبيرة." : "Use during major operational updates."}</span></div></label></div></section>

      <section className="editor-card ai-admin-settings"><div className="card-head"><div><span className="eyebrow">TIJVORYA AI</span><h3>{locale === "ar" ? "الذكاء الاصطناعي" : "Artificial intelligence"}</h3></div><div className={`ai-connection-badge ${status?.mode ?? "checking"}`}>{checking ? <LoaderCircle className="spin" /> : status?.mode === "live" ? <CheckCircle2 /> : status?.mode === "demo" ? <Sparkles /> : <CircleOff />}<span>{checking ? (locale === "ar" ? "جارٍ الفحص" : "Checking") : status?.mode === "live" ? (locale === "ar" ? `متصل بـ OpenAI — ${status.model}` : `OpenAI connected — ${status.model}`) : status?.mode === "demo" ? (locale === "ar" ? "مولد محلي احتياطي — أضف مفتاح OpenAI لتفعيل الخدمة المباشرة" : "Local fallback generator — add an OpenAI key for live AI") : (locale === "ar" ? "غير متصل" : "Not connected")}</span></div></div>
        <div className="ai-governance-note"><ShieldCheck /><div><strong>{locale === "ar" ? "سياسة القرار البشري" : "Human decision policy"}</strong><p>{locale === "ar" ? "الذكاء الاصطناعي يقترح ويصنّف فقط. لا ينشر منتجًا أو ريلز ولا يعتمد محتوى دون قرار التاجر أو الإدارة." : "AI suggests and classifies only. It never publishes or approves content without merchant or admin action."}</p></div></div>
        <div className="admin-toggle-list"><label><input type="checkbox" checked={settings.aiEnabled} onChange={(event) => setSettings({ ...settings, aiEnabled: event.target.checked })} /><div><strong>{locale === "ar" ? "تشغيل Tijvorya AI" : "Enable Tijvorya AI"}</strong><span>{locale === "ar" ? "المفتاح الرئيسي لجميع الأدوات الذكية." : "Master switch for all AI tools."}</span></div></label><label><input type="checkbox" disabled={!settings.aiEnabled} checked={settings.aiProductWriterEnabled} onChange={(event) => setSettings({ ...settings, aiProductWriterEnabled: event.target.checked })} /><div><strong>{locale === "ar" ? "كاتب وصف المنتجات" : "Product copy writer"}</strong><span>{locale === "ar" ? "إنشاء وصف عربي وإنجليزي داخل نموذج المنتج." : "Generate Arabic and English copy in the product form."}</span></div></label><label><input type="checkbox" disabled={!settings.aiEnabled} checked={settings.aiReelWriterEnabled} onChange={(event) => setSettings({ ...settings, aiReelWriterEnabled: event.target.checked })} /><div><strong>{locale === "ar" ? "كاتب كابشن الريلز" : "Reel caption writer"}</strong><span>{locale === "ar" ? "إنشاء Hook وكابشن وهاشتاقات من بيانات المنتج." : "Generate hooks, captions and hashtags from product data."}</span></div></label><label><input type="checkbox" disabled={!settings.aiEnabled} checked={settings.aiModerationEnabled} onChange={(event) => setSettings({ ...settings, aiModerationEnabled: event.target.checked })} /><div><strong>{locale === "ar" ? "فحص سلامة ومساعدة المراجعة" : "Safety and review assistance"}</strong><span>{locale === "ar" ? "فحص النص والغلاف وتقديم توصية مساعدة لإدارة الريلز." : "Check captions and covers and assist the admin moderation queue."}</span></div></label></div>
        <label className="field ai-limit-field"><span>{locale === "ar" ? "الحد اليومي المقترح لكل مستخدم" : "Suggested daily limit per user"}</span><input type="number" min={1} max={1000} value={settings.aiDailyRequestLimit} onChange={(event) => setSettings({ ...settings, aiDailyRequestLimit: Number(event.target.value) })} /><small>{locale === "ar" ? "يُستخدم كسياسة تشغيلية، بينما يطبق الخادم أيضًا حدًا مؤقتًا للحماية." : "Used as an operating policy; the server also applies a temporary protection limit."}</small></label>
      </section>
      <div className="sticky-form-actions"><button className="button button-dark"><Bot />{locale === "ar" ? "حفظ إعدادات المنصة" : "Save platform settings"}</button>{!productionMode && <button type="button" className="button button-ghost" onClick={resetDemo}>{locale === "ar" ? "مسح البيانات المحلية" : "Clear local data"}</button>}</div>
    </form>
  </>;
}
